FROM python:3.11.4
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /postgres_to_es

COPY /requirements/etl.txt ./
ENV PATH="/app/.local/bin:${PATH}"
RUN pip install -r etl.txt

COPY /postgres_to_es/ ./

CMD ["python", "main.py"]