FROM python:3.11.4
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /src

COPY /requirements/sqlite_to_postgres.txt ./
ENV PATH="/app/.local/bin:${PATH}"
RUN pip install -r sqlite_to_postgres.txt

COPY /sqlite_to_postgres/ ./

CMD ["python", "load_data.py"]