on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    
    name: Hello world
  
    steps:

    - name: ls
      run: ls

    - name: Rename .env file 
      run: mv ./etl/.env.sample ./etl/.env

    - uses: actions/checkout@v3
    - uses: isbang/compose-action@v1.4.1
      with:
        compose-file: "./etl/docker-compose.tests.yml"

    - name: Attach to Newman
      run: docker attach etl-newman-1 