name: newman-tests

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Rename .env file
        run: mv ./etl/.env.sample ./etl/.env

      - name: Build
        run: docker-compose -f ./etl/docker-compose.tests.yml build

      - name: Up
        run: docker-compose -f ./etl/docker-compose.tests.yml up -d

      - name: Attach to Newman
        run: docker attach etl_newman_1
