on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    
    name: Hello world
  
    steps:

    - uses: actions/checkout@v3

    - name: Rename .env file 
      run: mv ./etl/.env.sample ./etl/.env

    - name: Build
        run: docker-compose -f ./etl/docker-compose.tests.yml build && docker-compose -d up

    - name: Attach to Newman
      run: docker attach etl-newman-1 